### ISSUE TITLE
Folding range provider for BEGIN/END and ?IF/?IFNOT blocks

### ISSUE THREAD

**Issue by Ben-Voris** [knovichikhin/vscode_tal#14]
A common idiom for comment blocks is to enclose them in ?IF/?IFNOT blocks, like so:

?IF 15
?IFNOT 15
I can write anything I want here as it's never compiled.
?ENDIF 15

Is it possible to treat this as comment block for highlighting?

**Comment by knovichikhin** [comment]
This extension does not understand language semantics. To do what you ask I would have to implement TAL parser - not a trivial task.

At the same time default Visual Studio Code C extension is doing the same thing.
C:
![image](https://user-images.githubusercontent.com/447868/94877312-2754bd80-0428-11eb-839a-6d410a1d1fd9.png)

TAL:
![image](https://user-images.githubusercontent.com/447868/94877330-350a4300-0428-11eb-836f-5c35aae6d465.png)

**Comment by Ben-Voris** [comment]
Thanks. I don't know what what was reasonable, I figured it didn't hurt to ask.

**Comment by knovichikhin** [comment]
Not a problem. It's always good to know what people want to see.

**Comment by Ben-Voris** [comment]
Could you create the down arrows that let me collapse `BEGIN`/`END` pairs for `?IF`/`?ENDIF` blocks ?
If you can, please, would you reopen this issue to implement that feature?

**Comment by knovichikhin** [comment]
It's possible to provide folding logic to VSCode. I'll take a look at it.
