### ISSUE TITLE
Language mode TAL or TACL prevents spellcheck with Spell Right

### ISSUE THREAD

**Issue by Ben-Voris** [knovichikhin/vscode_tal#24]
Install ban.spellright (v3.0.60) along with knovichikhin.tal (v0.7.10)

Create a new file and enter `chaging` (i.e., misspelling of `changing`). If necessary, change the language mode to Plain Text. You should see a spelling error. Change the language mode to TACL. I see the spelling error disappear, but it should not.

This happens for me with the default config, but I've also tried putting this in my global settings.json:

```jsonc
  "spellright.spellContextByClass": {
    "jsonc": "comments",
    "cpp": "comments strings",
    "c": "comments strings",
    "tal": "comments strings",
    "tacl": "body comments strings",
    "plaintext": "body comments strings",
    "markdown": "body comments strings"
  },
  "spellright.language": [
    "en"
  ],
  "spellright.documentTypes": [
    "jsonc",
    "markdown",
    "plaintext",
    "c",
    "cpp",
    "tal",
    "tacl",
    "shellscript"
  ],
```

**Comment by knovichikhin** [comment]
I looked at their source code and don't see where they get comments and string definition aside from the internal configuration per language.

So, when you configure "body comments strings" it does not actually know what to do with TAL or TACL.
You can configure a "code" parser for TAL. Like this:

```
    "spellright.parserByClass": {
        "tal": {
            "parser" : "code"
    },
```

And this at least handles strings. But "code" parser is made basically for C family of languages.

The only way I made it work is by modifying the code. It's too bad comment and string definition cannot be configured or at least I don't see a setting for it.

Configuration:

```
    "spellright.documentTypes": [
        "tal",
        "tacl"
    ],
```

Code change in (if on Windows): `C:\Users\USER\.vscode\extensions\ban.spellright-3.0.60\lib\doctype.js`

Function: `function fromLanguage(id)`

```
        case 'tal':
            return new Code_1.default({ comment_line: '--', string_inline: '"', string_quote: '""' });
        case 'tacl':
            return new Code_1.default({ comment_start: '{', comment_end: '}', comment_line: '==', string_inline: '"', string_quote: '""' });
```

This works. 

TAL:

![image](https://user-images.githubusercontent.com/447868/129989364-0f6fcdda-7c63-49de-b5d0-9f581deca20f.png)

TACL:

![image](https://user-images.githubusercontent.com/447868/129989387-57fb3c14-5b7a-4314-886a-3ba81e181ae9.png)

Maybe the maintainer will accept a patch? 500 people use TAL, 50 use TACL. 😆
