### ISSUE TITLE
TACL matches quotes when it shouldn't

### ISSUE THREAD

**Issue by Ben-Voris** [knovichikhin/vscode_tal#25]
This snippet

```text
#SET :cmd FOO "
#OUTPUT [:cmd]
#SET :cmd [:cmd] some more text"
```

Is rendered like this:

![image](https://user-images.githubusercontent.com/31499002/159819775-5b117a42-4649-4182-9241-a1f2503caf55.png)

Quote characters have no special meaning after a builtin.

The workaround I use is:

```text
#SET :cmd FOO "
== The trailing quote of this comment prevents bad quote matching by the TACL plugin"
#OUTPUT [:cmd]
#SET :cmd [:cmd] some more text"
```

Which is rendered like so:

![image](https://user-images.githubusercontent.com/31499002/159819989-161839ad-7020-4f96-b322-a88efb82b43a.png)

I was surprised that a quote in a comment balances a quote outside of comment.

**Comment by knovichikhin** [comment]
I updated TACL string handling from multi-line match to single line. That should prevent these kinds of issues. Multi-line string matching is fine for most languages, but TACL is very very special.

Please, update to version 0.7.11 and give it a try.

![image](https://user-images.githubusercontent.com/447868/159841620-b28038c0-1926-4d7e-bf19-902d611307d2.png)
